skip_gpg:
  true

rock_cache_dir:
  rocknsm_cache

rock_repo:
  2_1

rockscripts_branch:
  devel

rockdashboards_branch:
  devel

pulledpork_release:
  0.7.2

package_groups:
  - core
  - anaconda-tools

download_packages:
  - vim-enhanced
  - nano
  - tmux
  - git
  - bzip2
  - ansible
  - rock
  - rock-release
  - initial-setup
  - yum-utils
  - openscap
  - openscap-scanner
  - scap-security-guide
  - pam_pkcs11
  - openssh-server
  - screen
  - shim-x64
  - bwm-ng
  - tcpreplay
  - tcpdump
  - bats
  - policycoreutils-python
  - htop
  - nmap-ncat
  - logrotate
  - bro
  - bro-plugin-kafka
  - bro-plugin-af_packet
  - GeoIP
  - GeoIP-update
  - suricata
  - suricata-update
  - stenographer
  - jq
  - docket
  - lighttpd
  - zookeeper
  - kafka
  - kafkacat
  - java-1.8.0-openjdk-headless
  - fsf
  - elasticsearch
  - logstash
  - kibana
  - metricbeat
  - filebeat
  - auditbeat
  - easy-rsa
  - python2-pyOpenSSL
  - python2-xkcdpass
